# Generated by Django 4.2.6 on 2024-03-30 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=31, null=True)),
                ('values', models.CharField(max_length=10, null=True)),
                ('icone', models.CharField(max_length=31, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Company Ceremony',
            },
        ),
        migrations.CreateModel(
            name='about_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'About Brand Slider',
            },
        ),
        migrations.CreateModel(
            name='about_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=31, null=True)),
                ('feature_details', models.CharField(max_length=127, null=True)),
                ('feature_icone', models.CharField(blank=True, max_length=31)),
                ('progress_title', models.CharField(max_length=31, null=True)),
                ('values', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Features & Experiences',
            },
        ),
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=31, null=True)),
                ('about_details', models.TextField(null=True)),
                ('about_details2', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('our_vision', models.TextField(max_length=510, null=True)),
                ('our_mission', models.TextField(max_length=510, null=True)),
                ('shifting_expriance_title', models.CharField(max_length=63, null=True)),
                ('expriance_details', models.CharField(max_length=510, null=True)),
                ('site_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'About Shifting',
            },
        ),
        migrations.CreateModel(
            name='blog_popular_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_tags_title', models.CharField(max_length=127, null=True)),
                ('categories_title', models.CharField(default='Default Title', max_length=127)),
            ],
            options={
                'verbose_name_plural': 'Blog Popular Tag & Categories',
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('date', models.DateField(max_length=31, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('descriptions', models.TextField(null=True)),
                ('link_types', models.CharField(max_length=31, null=True)),
                ('singal_blog_details', models.TextField(max_length=510, null=True)),
                ('singal_blog_image1', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('singal_blog_image2', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('singal_blog_image3', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('qoute', models.CharField(max_length=250, null=True)),
                ('person_name', models.CharField(max_length=31, null=True)),
                ('singal_blog_details2', models.TextField(max_length=510, null=True)),
                ('singal_blog_title', models.CharField(max_length=60, null=True)),
                ('singal_blog_image4', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('singal_blog_details3', models.TextField(max_length=510, null=True)),
                ('singal_blog_title2', models.CharField(max_length=60, null=True)),
                ('singal_blog_details4', models.TextField(max_length=510, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog List',
            },
        ),
        migrations.CreateModel(
            name='Booking_labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('worker_type', models.CharField(max_length=255)),
                ('working_time', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('booking_datetime', models.DateTimeField()),
                ('working_datetime', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Labour Booking List',
            },
        ),
        migrations.CreateModel(
            name='Booking_tec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('technician_type', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('booking_date_time', models.DateTimeField()),
                ('working_date_time', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Technician Booking List',
            },
        ),
        migrations.CreateModel(
            name='BookingCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('commercial_details', models.TextField()),
                ('address', models.TextField()),
                ('booking_date_time', models.DateTimeField()),
                ('shifting_date_time', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting Commercial Booking',
            },
        ),
        migrations.CreateModel(
            name='Bookinghome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('your_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('booking_datetime', models.DateTimeField()),
                ('shifting_datetime', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Home Booking Forms',
            },
        ),
        migrations.CreateModel(
            name='BookingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('acs_ton_items', models.CharField(max_length=255)),
                ('furniture_items', models.CharField(max_length=255)),
                ('glass_items', models.CharField(max_length=255)),
                ('melamine_items', models.CharField(max_length=255)),
                ('mattress_items', models.CharField(max_length=255)),
                ('others_items', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('booking_date_time', models.DateTimeField()),
                ('shifting_date_time', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting House Booking',
            },
        ),
        migrations.CreateModel(
            name='BookingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('acs_ton_items', models.CharField(max_length=255)),
                ('chair_tables_items', models.CharField(max_length=255)),
                ('computer_items', models.CharField(max_length=255)),
                ('monitor_items', models.CharField(max_length=255)),
                ('glass_items', models.CharField(max_length=255)),
                ('others_items', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('booking_date_time', models.DateTimeField()),
                ('shifting_date_time', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting Office Booking',
            },
        ),
        migrations.CreateModel(
            name='branch_barisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Barisal',
            },
        ),
        migrations.CreateModel(
            name='branch_chittagong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Chittagong',
            },
        ),
        migrations.CreateModel(
            name='branch_chittagong_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Chittagong City',
            },
        ),
        migrations.CreateModel(
            name='branch_dhaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Dhaka',
            },
        ),
        migrations.CreateModel(
            name='branch_dhaka_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Dhaka City',
            },
        ),
        migrations.CreateModel(
            name='branch_khulna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Khulna',
            },
        ),
        migrations.CreateModel(
            name='branch_mymensingh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Mymensingh ',
            },
        ),
        migrations.CreateModel(
            name='branch_rajshahi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Rajshahi',
            },
        ),
        migrations.CreateModel(
            name='branch_rangpur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Rangpur',
            },
        ),
        migrations.CreateModel(
            name='branch_sylhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number1', models.CharField(max_length=25, null=True, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Branch Sylhet',
            },
        ),
        migrations.CreateModel(
            name='contact_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_no', models.CharField(max_length=20, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('primary_email', models.EmailField(max_length=62, null=True)),
                ('email', models.EmailField(blank=True, max_length=62)),
                ('address', models.TextField(null=True)),
                ('office_time', models.CharField(max_length=126, null=True)),
                ('holiday', models.CharField(max_length=126, null=True)),
                ('form_title', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('top_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Contact Address & Logo',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('subject', models.CharField(max_length=63, null=True)),
                ('messages', models.TextField(null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('top_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('site_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'S. Couriers',
            },
        ),
        migrations.CreateModel(
            name='couriers_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=255)),
                ('cost_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'S. Couriers Services & Cost',
            },
        ),
        migrations.CreateModel(
            name='Covertruckdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T PickUp Cover Van',
            },
        ),
        migrations.CreateModel(
            name='home_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Home Sliders',
            },
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.FileField(null=True, upload_to='get_default_video_path')),
            ],
            options={
                'verbose_name_plural': 'Home Slider Videos',
            },
        ),
        migrations.CreateModel(
            name='labour_demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labour_Type', models.CharField(max_length=127, null=True)),
                ('inside_dhaka', models.CharField(max_length=127, null=True)),
                ('outside_dhaka', models.CharField(max_length=127, null=True)),
                ('onside_outside_dhaka', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Labour Demand',
            },
        ),
        migrations.CreateModel(
            name='labours_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Labour Type',
            },
        ),
        migrations.CreateModel(
            name='largeCovertruckdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T Large Cover Van',
            },
        ),
        migrations.CreateModel(
            name='Largtruckdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T Large Truck',
            },
        ),
        migrations.CreateModel(
            name='md',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designations', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('messages', models.TextField(null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=63)),
                ('instagram_link', models.CharField(blank=True, max_length=63)),
                ('google_link', models.CharField(blank=True, max_length=63)),
                ('twitter_link', models.CharField(blank=True, max_length=63)),
            ],
            options={
                'verbose_name_plural': 'Md & Ceo Message',
            },
        ),
        migrations.CreateModel(
            name='MediumCovertruckdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T Medium Cover Van',
            },
        ),
        migrations.CreateModel(
            name='Mediumtruckdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T Medium Truck',
            },
        ),
        migrations.CreateModel(
            name='notice_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Notice Descriptions',
            },
        ),
        migrations.CreateModel(
            name='notice_job_circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=127, null=True)),
                ('interview_date', models.CharField(max_length=127, null=True)),
                ('date', models.DateField(max_length=31, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('address', models.CharField(max_length=250, null=True)),
                ('interview_address', models.CharField(max_length=250, null=True)),
                ('interview_date_time', models.CharField(max_length=250, null=True)),
                ('note', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Notice Job Circulars',
            },
        ),
        migrations.CreateModel(
            name='our_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Home Our Services',
            },
        ),
        migrations.CreateModel(
            name='portfoliosCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=31, null=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Category',
            },
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=127, null=True)),
                ('questions_answer', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faq Questions',
            },
        ),
        migrations.CreateModel(
            name='securities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('sub_title', models.CharField(max_length=127, null=True)),
                ('top_descriptions', models.TextField(null=True)),
                ('top_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('descriptions1', models.TextField(max_length=510, null=True)),
                ('descriptions2', models.TextField(max_length=510, null=True)),
                ('site_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'S. Security',
            },
        ),
        migrations.CreateModel(
            name='SecurityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('security_type', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('booking_datetime', models.DateTimeField()),
                ('working_datetime', models.DateTimeField()),
                ('booking_details', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'S. Security Bookings List',
            },
        ),
        migrations.CreateModel(
            name='shifting_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('sub_title', models.CharField(max_length=127, null=True)),
                ('top_descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('descriptions', models.TextField(null=True)),
                ('descriptions2', models.CharField(max_length=510, null=True)),
                ('site_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'S. Shifting Services',
            },
        ),
        migrations.CreateModel(
            name='shifting_houseser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('top_details', models.TextField(max_length=510, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting House',
            },
        ),
        migrations.CreateModel(
            name='shifting_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'S. Shifting Office',
            },
        ),
        migrations.CreateModel(
            name='shifting_other_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=127, null=True)),
                ('inside_dhaka', models.CharField(max_length=127, null=True)),
                ('outside_dhaka', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting H/O/C Other Cost',
            },
        ),
        migrations.CreateModel(
            name='shifting_transport_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=127, null=True)),
                ('inside_dhaka', models.CharField(max_length=127, null=True)),
                ('outside_dhaka', models.CharField(max_length=127, null=True)),
                ('per_km_cost', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Shifting H/O/C Transport Cost',
            },
        ),
        migrations.CreateModel(
            name='shiftingc_ommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'S. Shifting Commercial',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subscribe Customers',
            },
        ),
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, null=True)),
                ('designation', models.CharField(max_length=31, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('facebook_link', models.CharField(default='Write..', max_length=63)),
                ('twitter_link', models.CharField(default='Write..', max_length=63)),
                ('instagram_link', models.CharField(default='Write..', max_length=63)),
            ],
            options={
                'verbose_name_plural': 'Team Members List',
            },
        ),
        migrations.CreateModel(
            name='technician_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Technician Category',
            },
        ),
        migrations.CreateModel(
            name='technician_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=127, null=True)),
                ('inside_dhaka', models.CharField(max_length=127, null=True)),
                ('outside_dhaka', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S. Technician Chart ',
            },
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, null=True)),
                ('designation', models.CharField(max_length=31, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('message', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='truck_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=127, null=True)),
                ('truck_title', models.CharField(max_length=510, null=True)),
                ('descriptions', models.TextField(max_length=510, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('fixed_amount', models.CharField(max_length=127, null=True)),
                ('per_km_amount', models.CharField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'S.T PickUp Truck',
            },
        ),
        migrations.CreateModel(
            name='technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('sub_title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('top_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('repair_title', models.CharField(max_length=127, null=True)),
                ('repair_details', models.TextField(max_length=1000, null=True)),
                ('bottom_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('bottom_image2', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('bootom_title', models.CharField(max_length=127, null=True)),
                ('bootom_details', models.TextField(max_length=1010, null=True)),
                ('contact_details', models.CharField(max_length=255, null=True)),
                ('repair_manue1', models.CharField(max_length=127, null=True)),
                ('repair_manue2', models.CharField(max_length=127, null=True)),
                ('repair_manue3', models.CharField(max_length=127, null=True)),
                ('repair_manue4', models.CharField(max_length=127, null=True)),
                ('repair_manue5', models.CharField(blank=True, max_length=127)),
                ('repair_manue6', models.CharField(blank=True, max_length=127)),
                ('category_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.technician_category')),
            ],
            options={
                'verbose_name_plural': 'S. Technician Item',
            },
        ),
        migrations.CreateModel(
            name='portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, null=True)),
                ('category', models.CharField(max_length=31, null=True)),
                ('image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('category_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.portfolioscategory')),
            ],
            options={
                'verbose_name_plural': 'Portfolio List',
            },
        ),
        migrations.CreateModel(
            name='labours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('main_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('sub_title', models.CharField(max_length=127, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('descriptions2', models.TextField(max_length=510, null=True)),
                ('descriptions3', models.TextField(max_length=510, null=True)),
                ('site_title', models.CharField(max_length=127, null=True)),
                ('site_details', models.CharField(max_length=510, null=True)),
                ('category_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.labours_type')),
            ],
            options={
                'verbose_name_plural': 'S. Labour list',
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('blog_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shifting.blogs')),
            ],
            options={
                'verbose_name_plural': 'Blog Comments',
            },
        ),
    ]
